export const tools = [
  {
    id: "1",
    icon: <i className='fa fa-home text-xl font-bold'></i>,
    link: "/dashboard",
    label: "Home",
    color: "",
  },
  {
    id: "2",
    icon: <i className='fa fa-book-open-reader text-xl font-bold'></i>,
    link: "../tools/library/",
    label: "Library",
    color: "text-red-400",
  },
  {
    id: "3",
    icon: <i className='fa fa-plus text-xl font-bold'></i>,
    link: "/dashboard",
    label: "Add",
    color: "",
  },
  {
    id: "4",
    icon: <i className='fa fa-users-line text-xl font-bold'></i>,
    link: "../tools/myteams/",
    label: "Teams",
    color: "text-pink-600",
  },
  {
    id: "5",
    icon: <i className='fa-solid fa-book text-xl font-bold'></i>,
    link: "../tools/ucs/",
    label: "UCS",
    color: "text-yellow-600",
  },
  {
    id: "6",
    icon: <i className='fa-solid fa-earth-americas text-xl font-bold'></i>,
    link: "../tools/academia/",
    label: "Academia",
    color: "text-indigo-600",
  },
  {
    id: "7",
    icon: <i className='fa-solid fa-square-h text-2xl font-bold'></i>,
    link: "../tools/hr/",
    label: "HR",
    color: "text-green-600",
  },
  {
    id: "8",

    icon: <i className='fa fa-graduation-cap text-2xl font-bold'></i>,
    link: "../tools/trainees/",
    label: "Trainees",
    color: "text-blue-600",
  },
  // {
  //   id: "9",
  //   icon: <i className='fa-solid fa-warehouse text-2xl font-bold'></i>,
  //   link: "../tools/inventory/",
  //   label: "Inventory",
  //   color: "text-blue-600",
  // },
  {
    id: "9",
    icon: <i className='fa fa-university text-2xl font-bold'></i>,
    link: "../tools/finance/",
    label: "Finance",
    color: "text-green-500",
  },

  {
    id: "10",
    icon: <i className='fa fa-cart-plus text-2xl font-bold'></i>,
    link: "../tools/btob/",
    label: "B2B",
    color: "text-pink-400",
  },
  {
    id: "11",
    icon: <i className='fa-solid fa-desktop text-2xl font-bold'></i>,
    link: "../tools/settings/",
    label: "Partners",
    color: "text-blue-600",
  },

  {
    id: "12",
    icon: <i className='fa-solid fa-desktop text-2xl font-bold'></i>,
    link: "../tools/settings/",
    label: "Partner",
    color: "text-blue-500",
  },
  {
    id: "13",
    icon: <i className='fa fa-cog text-2xl font-bold'></i>,
    link: "../tools/finance/",
    label: "Settings",
    color: "text-blue-500",
  },
  {
    id: "14",
    icon: <i className='fa fa-comment text-2xl font-bold'></i>,
    link: "../tools/chat/",
    label: "Chat",
    color: "text-slate-300",
  },
];
